name: exllama
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.1=hd590300_1
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.41.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==1.4.0
      - accelerate==0.21.0
      - aiofiles==23.1.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - altair==5.0.1
      - anyio==3.7.1
      - appdirs==1.4.4
      - asttokens==2.2.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - auto-gptq==0.3.0+cu117
      - backcall==0.2.0
      - bitsandbytes==0.40.2
      - blinker==1.6.2
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cmake==3.27.0
      - colorama==0.4.6
      - contourpy==1.1.0
      - cycler==0.11.0
      - datasets==2.13.1
      - decorator==5.1.1
      - dill==0.3.6
      - diskcache==5.6.1
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - exceptiongroup==1.1.2
      - executing==1.2.0
      - exllama==0.0.7+cu117
      - fastapi==0.95.2
      - ffmpy==0.3.1
      - filelock==3.12.2
      - flask==2.3.2
      - flask-cloudflared==0.0.12
      - flexgen==0.1.7
      - fonttools==4.41.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - gradio==3.33.1
      - gradio-client==0.2.5
      - grpcio==1.56.2
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - idna==3.4
      - ipdb==0.13.13
      - ipython==8.14.0
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.3.1
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - kiwisolver==1.4.4
      - linkify-it-py==2.0.2
      - lit==16.0.6
      - llama-cpp-python==0.1.73
      - llama-cpp-python-cuda==0.1.73+cu117
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.25.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - oauthlib==3.2.2
      - openai==0.27.8
      - orjson==3.9.2
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - pathtools==0.1.2
      - peft==0.4.0.dev0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - prompt-toolkit==3.0.39
      - protobuf==4.23.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pulp==2.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.11
      - pydub==0.25.1
      - pygments==2.15.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-multipart==0.0.6
      - pytz==2023.3
      - pyyaml==6.0.1
      - referencing==0.30.0
      - regex==2023.6.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rouge==1.0.1
      - rpds-py==0.9.2
      - rsa==4.9
      - safetensors==0.3.1
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - semantic-version==2.10.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.28.1
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - stack-data==0.6.2
      - starlette==0.27.0
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - threadpoolctl==3.2.0
      - tiktoken==0.4.0
      - tokenizers==0.13.3
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.31.0
      - triton==2.0.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - uc-micro-py==1.0.2
      - urllib3==1.26.16
      - uvicorn==0.23.1
      - wandb==0.15.5
      - wcwidth==0.2.6
      - websockets==11.0.3
      - werkzeug==2.3.6
      - xxhash==3.2.0
      - yarl==1.9.2
prefix: /home/ubuntu/mambaforge/envs/exllama
